<?php

namespace SchoolBundle\Repository;

/**
 * AnneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeRepository extends \Doctrine\ORM\EntityRepository
{
}
