<?php

namespace SchoolBundle\Repository;

/**
 * EnsMatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnsMatRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByEnseignant($id)
    {
        $qb = $this->createQueryBuilder('c');
      
        $qb->where('c.enseignant = :id')
              ->setParameter('id', $id);
        return $qb;
    }   
}
