<?php

namespace SchoolBundle\Repository;

/**
 * EnsMatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnsMatRepository extends \Doctrine\ORM\EntityRepository
{
}
