<?php

namespace SchoolBundle\Repository;

/**
 * HorraireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorraireRepository extends \Doctrine\ORM\EntityRepository
{
}
