<?php

namespace SchoolBundle\Repository;

/**
 * JourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourRepository extends \Doctrine\ORM\EntityRepository
{
}
