<?php

namespace SchoolBundle\Repository;

/**
 * MatiereEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereEvaluationRepository extends \Doctrine\ORM\EntityRepository
{

}
