<?php

namespace SchoolBundle\Repository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends \Doctrine\ORM\EntityRepository
{

	public function findById($id)
    {
        $qb = $this->createQueryBuilder('m');
      
        $qb->where('m.id = :id')
              ->setParameter('id', $id);
        return $qb;
    }  

    public function findByArrayId($id)
    {
        $qb = $this->createQueryBuilder('m');
      
       // $qb->where('m.id in (:id)')
        $qb->add('where', $qb->expr()->in('m.id', $id));
        //      ->setParameter('id', $id, \Doctrine\DBAL\Connection::PARAM_STR_ARRAY);
        return $qb;
    }

 



}
