<?php

namespace UserBundle\Repository;

/**
 * EleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseignantRepository extends \Doctrine\ORM\EntityRepository
{
}
