<?php

namespace UserBundle\Repository;

/**
 * ParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentalRepository extends \Doctrine\ORM\EntityRepository
{
}
