<?php

namespace UserBundle\Repository;

/**
 * RetardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetardRepository extends \Doctrine\ORM\EntityRepository
{
}
